export const collaborativeClusterLabels = {
  guitarNarrative: "guitar-led listener overlap",
  grooveCircuit: "dance-floor crossover",
  globalPulse: "cross-cultural discovery graph",
  altSoul: "left-field soul affinity",
} as const;

export type CollaborativeCluster = keyof typeof collaborativeClusterLabels;

export interface TrackProfile {
  id: string;
  title: string;
  artist: string;
  genre: string;
  region: string;
  bpm: number;
  energy: number;
  danceability: number;
  electronic: number;
  valence: number;
  groove: number;
  guitarFocus: number;
  globalFusion: number;
  discovery: number;
  tags: string[];
  modeHints: string[];
  chordMatches: string[];
  soloCue: string;
  narrative: string;
  collaborative: Record<CollaborativeCluster, number>;
}

export interface MoodPreset {
  id: string;
  label: string;
  blurb: string;
  featureBias: Partial<Record<AdjustableFeatureKey, number>>;
  tags: string[];
}

export interface StyleBlendProfile {
  id: string;
  label: string;
  note: string;
  featureBias: Partial<Record<AdjustableFeatureKey, number>>;
  tags: string[];
  modeHints: string[];
  collaborativeBias: Partial<Record<CollaborativeCluster, number>>;
}

export interface ChordProgressionPreset {
  id: string;
  label: string;
  chords: string;
  explanation: string;
  featureBias: Partial<Record<AdjustableFeatureKey, number>>;
  tags: string[];
  compatibleModes: string[];
}

export type AdjustableFeatureKey =
  | "energy"
  | "tempo"
  | "danceability"
  | "electronic"
  | "valence"
  | "groove"
  | "guitarFocus"
  | "globalFusion";

export const moodPresets: MoodPreset[] = [
  {
    id: "late-night",
    label: "Late-Night Lift",
    blurb: "Warm pockets, elegant harmony, enough pulse to keep the room leaning in.",
    featureBias: { energy: -6, tempo: -8, danceability: 4, electronic: -6, valence: 2, groove: 8 },
    tags: ["after-hours", "neo-soul", "smoked textures"],
  },
  {
    id: "festival",
    label: "Festival Voltage",
    blurb: "Bigger hooks, faster tempos, and rhythmic payoff that lands immediately.",
    featureBias: { energy: 14, tempo: 12, danceability: 10, electronic: 8, valence: 6, groove: 5 },
    tags: ["anthemic", "peak-time", "kinetic"],
  },
  {
    id: "focus",
    label: "Cinematic Focus",
    blurb: "Detailed arrangements, lower vocal clutter, and strong harmonic identity.",
    featureBias: { energy: -10, tempo: -4, danceability: -8, electronic: -4, groove: 4, guitarFocus: 8 },
    tags: ["instrumental", "headphones", "harmonic detail"],
  },
  {
    id: "global-hop",
    label: "Global Hop",
    blurb: "Cross-border transitions that keep groove continuity while widening the palette.",
    featureBias: { energy: 4, tempo: 3, danceability: 8, groove: 8, globalFusion: 18 },
    tags: ["diaspora", "traveling groove", "hybrid rhythm"],
  },
];

export const styleBlendProfiles: StyleBlendProfile[] = [
  {
    id: "dire-straits",
    label: "Dire Straits",
    note: "Fingerstyle articulation, melodic restraint, and road-film guitar storytelling.",
    featureBias: { guitarFocus: 16, energy: 2, tempo: -4, electronic: -14, groove: 4 },
    tags: ["fingerstyle", "narrative soloing", "roots groove"],
    modeHints: ["Mixolydian", "Dorian"],
    collaborativeBias: { guitarNarrative: 0.16, altSoul: 0.04 },
  },
  {
    id: "kaytranada",
    label: "Kaytranada",
    note: "Swing-forward low end, club intelligence, and R&B-adjacent motion.",
    featureBias: { energy: 8, danceability: 14, electronic: 12, groove: 10, valence: 4 },
    tags: ["broken-house", "bounce", "club-soul"],
    modeHints: ["Dorian", "Minor pentatonic"],
    collaborativeBias: { grooveCircuit: 0.18, altSoul: 0.12 },
  },
  {
    id: "rosalia",
    label: "Rosalia",
    note: "Flamenco detail pushed through modern production architecture.",
    featureBias: { energy: 7, danceability: 4, electronic: 9, guitarFocus: 6, globalFusion: 10 },
    tags: ["flamenco", "percussive phrasing", "modern Iberian"],
    modeHints: ["Phrygian", "Dorian"],
    collaborativeBias: { globalPulse: 0.16, altSoul: 0.06 },
  },
  {
    id: "khruangbin",
    label: "Khruangbin",
    note: "Minimal guitar hooks, world-leaning groove, and patient repetition.",
    featureBias: { energy: -2, danceability: 6, electronic: -8, groove: 8, guitarFocus: 9, globalFusion: 12 },
    tags: ["desert groove", "minimalist guitar", "world psych"],
    modeHints: ["Mixolydian", "Minor pentatonic"],
    collaborativeBias: { guitarNarrative: 0.08, globalPulse: 0.2 },
  },
  {
    id: "hiatus-kaiyote",
    label: "Hiatus Kaiyote",
    note: "Elastic harmony, left-field soul, and rhythmic surprise without chaos.",
    featureBias: { energy: 4, danceability: 2, groove: 12, guitarFocus: 4, valence: 3 },
    tags: ["future soul", "odd-meter feel", "harmonic color"],
    modeHints: ["Lydian", "Dorian"],
    collaborativeBias: { altSoul: 0.2, grooveCircuit: 0.08 },
  },
];

export const chordProgressionPresets: ChordProgressionPreset[] = [
  {
    id: "neo-soul-vamp",
    label: "Neo-Soul Extensions",
    chords: "Em9 - A13 - Cmaj7#11",
    explanation: "Extended harmony with enough space for tasteful upper-structure movement.",
    featureBias: { groove: 8, guitarFocus: 8, danceability: 3, valence: 2 },
    tags: ["extended chords", "pocket", "warm Rhodes"],
    compatibleModes: ["Dorian", "Lydian"],
  },
  {
    id: "mixolydian-pocket",
    label: "Mixolydian Funk Turnaround",
    chords: "A7 - D9 - E13",
    explanation: "Dominant-pocket phrasing that wants ghost notes, syncopation, and space.",
    featureBias: { energy: 6, tempo: 5, danceability: 10, groove: 12, guitarFocus: 6 },
    tags: ["dominant vamp", "syncopated rhythm", "funk pocket"],
    compatibleModes: ["Mixolydian", "Major pentatonic"],
  },
  {
    id: "andalusian",
    label: "Andalusian Cadence",
    chords: "Am - G - F - E",
    explanation: "Strong Iberian gravity with dramatic pull into the tonic.",
    featureBias: { energy: 7, guitarFocus: 10, globalFusion: 12, valence: -2 },
    tags: ["iberian", "dramatic cadence", "hand percussion"],
    compatibleModes: ["Phrygian", "Harmonic minor"],
  },
  {
    id: "minor-ii-v",
    label: "Minor II-V Tension",
    chords: "Dm7b5 - G7alt - Cm9",
    explanation: "Jazz-minded tension and release with room for altered dominant color.",
    featureBias: { energy: -3, groove: 6, guitarFocus: 7, valence: -1 },
    tags: ["altered dominant", "jazz harmony", "late-night phrasing"],
    compatibleModes: ["Dorian", "Melodic minor"],
  },
  {
    id: "pentatonic-drive",
    label: "Pentatonic Drive",
    chords: "Bm7 - E9",
    explanation: "Direct, hook-friendly motion for rhythmic guitar leads and vocal doubles.",
    featureBias: { energy: 9, tempo: 6, danceability: 7, guitarFocus: 5, groove: 7 },
    tags: ["riff-forward", "vocal doubles", "hook-driven"],
    compatibleModes: ["Minor pentatonic", "Mixolydian"],
  },
];

export const sampleTracks: TrackProfile[] = [
  {
    id: "valencia-afterglow",
    title: "Valencia Afterglow",
    artist: "Streetcar Signal",
    genre: "Neo-Soul / Flamenco",
    region: "Valencia, Spain",
    bpm: 104,
    energy: 62,
    danceability: 55,
    electronic: 24,
    valence: 58,
    groove: 72,
    guitarFocus: 94,
    globalFusion: 78,
    discovery: 44,
    tags: ["neo-soul", "flamenco", "fingerstyle", "late-night", "warm brass"],
    modeHints: ["Dorian", "Phrygian"],
    chordMatches: ["neo-soul-vamp", "andalusian", "minor-ii-v"],
    soloCue: "Blend Dorian phrasing with a Phrygian turnaround on the E cadence.",
    narrative: "A nylon-string front line over brushed pocket and brass swells.",
    collaborative: { guitarNarrative: 0.92, grooveCircuit: 0.42, globalPulse: 0.78, altSoul: 0.66 },
  },
  {
    id: "porto-chrome",
    title: "Porto Chrome",
    artist: "Atlas Motel",
    genre: "Balearic Disco / Indie",
    region: "Porto, Portugal",
    bpm: 118,
    energy: 71,
    danceability: 79,
    electronic: 52,
    valence: 67,
    groove: 76,
    guitarFocus: 46,
    globalFusion: 48,
    discovery: 39,
    tags: ["balearic", "indie-disco", "coastal", "glassy synths", "sunset"],
    modeHints: ["Mixolydian", "Major pentatonic"],
    chordMatches: ["mixolydian-pocket", "pentatonic-drive"],
    soloCue: "Lean on Mixolydian double-stops and rhythmic octave shapes.",
    narrative: "Poolside guitars and clipped synth bass built for open-air sets.",
    collaborative: { guitarNarrative: 0.46, grooveCircuit: 0.8, globalPulse: 0.5, altSoul: 0.38 },
  },
  {
    id: "copper-echoes",
    title: "Copper Echoes",
    artist: "North Line Parade",
    genre: "Guitar Noir / Art Rock",
    region: "Leeds, UK",
    bpm: 96,
    energy: 48,
    danceability: 39,
    electronic: 18,
    valence: 34,
    groove: 52,
    guitarFocus: 88,
    globalFusion: 28,
    discovery: 56,
    tags: ["art-rock", "guitar-noir", "cinematic", "moody", "narrative"],
    modeHints: ["Dorian", "Minor pentatonic"],
    chordMatches: ["minor-ii-v", "pentatonic-drive"],
    soloCue: "Stay sparse, then open up with minor pentatonic bends over the turnaround.",
    narrative: "A dry guitar lead and tense rhythm section made for headphone listening.",
    collaborative: { guitarNarrative: 0.86, grooveCircuit: 0.22, globalPulse: 0.16, altSoul: 0.44 },
  },
  {
    id: "sunline-circuit",
    title: "Sunline Circuit",
    artist: "Kudu Electric",
    genre: "Afro-Funk / Alt Dance",
    region: "Lagos, Nigeria",
    bpm: 121,
    energy: 84,
    danceability: 91,
    electronic: 46,
    valence: 72,
    groove: 89,
    guitarFocus: 37,
    globalFusion: 83,
    discovery: 63,
    tags: ["afro-funk", "alt-dance", "percussion", "festival", "hooky bass"],
    modeHints: ["Mixolydian", "Major pentatonic"],
    chordMatches: ["mixolydian-pocket", "pentatonic-drive"],
    soloCue: "Use Mixolydian sixths and rhythmic call-and-response motifs.",
    narrative: "A forward-leaning groove record with stacked percussion and elastic bass.",
    collaborative: { guitarNarrative: 0.28, grooveCircuit: 0.94, globalPulse: 0.96, altSoul: 0.44 },
  },
  {
    id: "mirador-bloom",
    title: "Mirador Bloom",
    artist: "Aurora District",
    genre: "Latin Electronica / House",
    region: "Barcelona, Spain",
    bpm: 124,
    energy: 79,
    danceability: 86,
    electronic: 78,
    valence: 70,
    groove: 82,
    guitarFocus: 22,
    globalFusion: 68,
    discovery: 45,
    tags: ["house", "latin-electronica", "club", "night-drive", "sunrise"],
    modeHints: ["Dorian", "Minor pentatonic"],
    chordMatches: ["neo-soul-vamp", "pentatonic-drive"],
    soloCue: "Keep the melody modal and rhythmic; let the groove do the talking.",
    narrative: "Mediterranean percussion threaded through a polished club chassis.",
    collaborative: { guitarNarrative: 0.18, grooveCircuit: 0.91, globalPulse: 0.72, altSoul: 0.41 },
  },
  {
    id: "blue-hour-transit",
    title: "Blue Hour Transit",
    artist: "Harbor Saints",
    genre: "Neo-Soul / Jazz-Hop",
    region: "Oakland, USA",
    bpm: 92,
    energy: 43,
    danceability: 52,
    electronic: 31,
    valence: 49,
    groove: 67,
    guitarFocus: 62,
    globalFusion: 31,
    discovery: 34,
    tags: ["neo-soul", "jazz-hop", "headphones", "warm keys", "laid-back"],
    modeHints: ["Dorian", "Lydian"],
    chordMatches: ["neo-soul-vamp", "minor-ii-v"],
    soloCue: "Target upper extensions and let the phrasing sit slightly behind the beat.",
    narrative: "Soft-focus keys, tight drums, and enough harmonic color to reward repeat listens.",
    collaborative: { guitarNarrative: 0.54, grooveCircuit: 0.46, globalPulse: 0.24, altSoul: 0.88 },
  },
  {
    id: "atlas-silk",
    title: "Atlas Silk",
    artist: "Sahara Type",
    genre: "Gnawa / Electronica",
    region: "Essaouira, Morocco",
    bpm: 110,
    energy: 66,
    danceability: 64,
    electronic: 58,
    valence: 54,
    groove: 78,
    guitarFocus: 34,
    globalFusion: 94,
    discovery: 72,
    tags: ["gnawa", "electronica", "trance pulse", "ritual groove", "global"],
    modeHints: ["Phrygian", "Dorian"],
    chordMatches: ["andalusian", "neo-soul-vamp"],
    soloCue: "Use repetitive modal fragments and emphasize the trance-like root motion.",
    narrative: "Ceremonial call-and-response reimagined for a modern low-end system.",
    collaborative: { guitarNarrative: 0.22, grooveCircuit: 0.66, globalPulse: 0.97, altSoul: 0.42 },
  },
  {
    id: "midnight-cable",
    title: "Midnight Cable",
    artist: "Lattice Palm",
    genre: "Synthwave / Alternative R&B",
    region: "Paris, France",
    bpm: 114,
    energy: 72,
    danceability: 71,
    electronic: 84,
    valence: 52,
    groove: 74,
    guitarFocus: 21,
    globalFusion: 36,
    discovery: 37,
    tags: ["synthwave", "alt-rnb", "night-drive", "glossy", "retro-futurist"],
    modeHints: ["Dorian", "Minor pentatonic"],
    chordMatches: ["neo-soul-vamp", "pentatonic-drive"],
    soloCue: "Short melodic motifs and octave lines work better than dense runs here.",
    narrative: "Chrome-plated synths, hushed vocals, and a very deliberate low-end contour.",
    collaborative: { guitarNarrative: 0.16, grooveCircuit: 0.78, globalPulse: 0.31, altSoul: 0.74 },
  },
  {
    id: "marigold-theory",
    title: "Marigold Theory",
    artist: "West Pier",
    genre: "Indie Soul / Art Pop",
    region: "Bristol, UK",
    bpm: 108,
    energy: 58,
    danceability: 59,
    electronic: 42,
    valence: 56,
    groove: 65,
    guitarFocus: 58,
    globalFusion: 34,
    discovery: 43,
    tags: ["indie-soul", "art-pop", "textural", "hooky", "warm vocals"],
    modeHints: ["Lydian", "Dorian"],
    chordMatches: ["neo-soul-vamp", "minor-ii-v"],
    soloCue: "Float between Lydian color tones and simpler pentatonic landing notes.",
    narrative: "A melodic indie frame with enough harmonic spice to stay sophisticated.",
    collaborative: { guitarNarrative: 0.52, grooveCircuit: 0.58, globalPulse: 0.24, altSoul: 0.79 },
  },
  {
    id: "cassette-tides",
    title: "Cassette Tides",
    artist: "Sol Meridian",
    genre: "MPB / Broken Beat",
    region: "Sao Paulo, Brazil",
    bpm: 102,
    energy: 57,
    danceability: 66,
    electronic: 36,
    valence: 63,
    groove: 74,
    guitarFocus: 64,
    globalFusion: 82,
    discovery: 58,
    tags: ["mpb", "broken beat", "sunlit", "jazzy", "brazilian"],
    modeHints: ["Lydian", "Major pentatonic"],
    chordMatches: ["neo-soul-vamp", "mixolydian-pocket"],
    soloCue: "Phrase melodically, then answer with rhythmic chord stabs.",
    narrative: "A breezy vocal cut that hides highly detailed rhythmic architecture.",
    collaborative: { guitarNarrative: 0.58, grooveCircuit: 0.62, globalPulse: 0.87, altSoul: 0.64 },
  },
  {
    id: "neon-cante-jondo",
    title: "Neon Cante Jondo",
    artist: "Faro Motor Club",
    genre: "Flamenco Fusion / Alt Pop",
    region: "Seville, Spain",
    bpm: 128,
    energy: 86,
    danceability: 75,
    electronic: 69,
    valence: 61,
    groove: 79,
    guitarFocus: 71,
    globalFusion: 88,
    discovery: 64,
    tags: ["flamenco", "alt-pop", "club", "dramatic", "percussive handclaps"],
    modeHints: ["Phrygian", "Harmonic minor"],
    chordMatches: ["andalusian", "pentatonic-drive"],
    soloCue: "Alternate Phrygian tension with harmonic minor resolves for the hook sections.",
    narrative: "A modern festival track with palmas, synth bass, and a razor-sharp topline.",
    collaborative: { guitarNarrative: 0.72, grooveCircuit: 0.83, globalPulse: 0.93, altSoul: 0.45 },
  },
  {
    id: "palm-wine-logic",
    title: "Palm Wine Logic",
    artist: "Delta Current",
    genre: "Highlife / Soul",
    region: "Accra, Ghana",
    bpm: 115,
    energy: 74,
    danceability: 82,
    electronic: 22,
    valence: 75,
    groove: 83,
    guitarFocus: 68,
    globalFusion: 86,
    discovery: 61,
    tags: ["highlife", "soul", "guitar-lines", "optimistic", "sunlit"],
    modeHints: ["Mixolydian", "Major pentatonic"],
    chordMatches: ["mixolydian-pocket", "pentatonic-drive"],
    soloCue: "Think melodic highlife guitar and keep the phrases smiling.",
    narrative: "Interlocking guitar lines and buoyant drums with wide crossover appeal.",
    collaborative: { guitarNarrative: 0.74, grooveCircuit: 0.84, globalPulse: 0.95, altSoul: 0.4 },
  },
  {
    id: "velvet-monsoon",
    title: "Velvet Monsoon",
    artist: "Pacific Drift",
    genre: "City Pop / Jazz-Funk",
    region: "Tokyo, Japan",
    bpm: 116,
    energy: 68,
    danceability: 78,
    electronic: 51,
    valence: 69,
    groove: 77,
    guitarFocus: 55,
    globalFusion: 57,
    discovery: 52,
    tags: ["city-pop", "jazz-funk", "sleek", "night skyline", "bass-led"],
    modeHints: ["Lydian", "Mixolydian"],
    chordMatches: ["mixolydian-pocket", "neo-soul-vamp"],
    soloCue: "Outline major-color extensions and resolve with tight rhythmic motifs.",
    narrative: "Polished city-pop bounce with a bass-first mix and clean chorus guitars.",
    collaborative: { guitarNarrative: 0.47, grooveCircuit: 0.82, globalPulse: 0.58, altSoul: 0.56 },
  },
  {
    id: "afterglow-index",
    title: "Afterglow Index",
    artist: "Halcyon Bureau",
    genre: "Alternative R&B / Electronic",
    region: "Los Angeles, USA",
    bpm: 98,
    energy: 53,
    danceability: 61,
    electronic: 72,
    valence: 46,
    groove: 68,
    guitarFocus: 26,
    globalFusion: 29,
    discovery: 35,
    tags: ["alt-rnb", "electronic", "low-lit", "sub-bass", "moody"],
    modeHints: ["Dorian", "Minor pentatonic"],
    chordMatches: ["neo-soul-vamp", "minor-ii-v"],
    soloCue: "Aim for short modal hooks with lots of negative space.",
    narrative: "Modern R&B weight with detailed ear-candy and tight kick placement.",
    collaborative: { guitarNarrative: 0.22, grooveCircuit: 0.74, globalPulse: 0.18, altSoul: 0.83 },
  },
  {
    id: "desert-polyrhythm",
    title: "Desert Polyrhythm",
    artist: "Caravan Echo",
    genre: "Global Jazz / Percussion",
    region: "Marrakech, Morocco",
    bpm: 130,
    energy: 77,
    danceability: 73,
    electronic: 41,
    valence: 57,
    groove: 92,
    guitarFocus: 44,
    globalFusion: 97,
    discovery: 78,
    tags: ["polyrhythm", "global-jazz", "percussion", "journey", "festival"],
    modeHints: ["Phrygian", "Dorian"],
    chordMatches: ["andalusian", "mixolydian-pocket"],
    soloCue: "Treat it like a rhythmic conversation more than a scalar sprint.",
    narrative: "Large-frame percussion writing that still lands like a song, not an exercise.",
    collaborative: { guitarNarrative: 0.26, grooveCircuit: 0.87, globalPulse: 0.99, altSoul: 0.38 },
  },
  {
    id: "signal-garden",
    title: "Signal Garden",
    artist: "Fifth Harbor",
    genre: "Cumbia Electronica / Indie",
    region: "Bogota, Colombia",
    bpm: 118,
    energy: 81,
    danceability: 87,
    electronic: 63,
    valence: 71,
    groove: 85,
    guitarFocus: 31,
    globalFusion: 89,
    discovery: 59,
    tags: ["cumbia-electronica", "indie", "percussive", "crowd-ready", "colorful"],
    modeHints: ["Mixolydian", "Major pentatonic"],
    chordMatches: ["mixolydian-pocket", "pentatonic-drive"],
    soloCue: "Keep it rhythmic, percussive, and melodic enough for instant recall.",
    narrative: "A festival-ready crossover with hand percussion and electronic lift.",
    collaborative: { guitarNarrative: 0.2, grooveCircuit: 0.92, globalPulse: 0.94, altSoul: 0.36 },
  },
  {
    id: "wireframe-samba",
    title: "Wireframe Samba",
    artist: "Prisma Norte",
    genre: "Future Bass / Samba",
    region: "Rio de Janeiro, Brazil",
    bpm: 126,
    energy: 85,
    danceability: 84,
    electronic: 88,
    valence: 73,
    groove: 81,
    guitarFocus: 19,
    globalFusion: 74,
    discovery: 62,
    tags: ["future-bass", "samba", "hybrid", "festival", "high gloss"],
    modeHints: ["Major pentatonic", "Dorian"],
    chordMatches: ["pentatonic-drive", "mixolydian-pocket"],
    soloCue: "Think vocal-like motifs and bright pentatonic resolutions.",
    narrative: "Maximalist drops with samba-informed percussion under the hood.",
    collaborative: { guitarNarrative: 0.12, grooveCircuit: 0.96, globalPulse: 0.82, altSoul: 0.28 },
  },
  {
    id: "mojave-aftermath",
    title: "Mojave Aftermath",
    artist: "Lantern Static",
    genre: "Americana / Groove Rock",
    region: "Austin, USA",
    bpm: 100,
    energy: 61,
    danceability: 47,
    electronic: 14,
    valence: 45,
    groove: 58,
    guitarFocus: 91,
    globalFusion: 22,
    discovery: 47,
    tags: ["americana", "groove-rock", "open-road", "guitar storytelling", "dusty"],
    modeHints: ["Mixolydian", "Minor pentatonic"],
    chordMatches: ["pentatonic-drive", "mixolydian-pocket"],
    soloCue: "A restrained Mixolydian lead with long-note bends will say more than speed.",
    narrative: "Road-movie guitars and a dry pocket that keeps the riff front and center.",
    collaborative: { guitarNarrative: 0.95, grooveCircuit: 0.29, globalPulse: 0.12, altSoul: 0.35 },
  },
];

export const defaultAmieState = {
  seedTrackId: "valencia-afterglow",
  moodId: "late-night",
  blendArtistId: "khruangbin",
  chordProgressionId: "neo-soul-vamp",
  energy: 66,
  tempo: 112,
  danceability: 67,
  electronic: 38,
  familiarity: 58,
  guitaristMode: true,
  globalPulse: true,
} as const;
