import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { ROUTE_META } from "./routeMeta";
import { CV_PROFILE } from "@/content/cv";

/**
 * The social card is a committed binary, generated by scripts/generate-og-card.mjs.
 *
 * A committed binary rots the moment someone edits the headline, and nobody
 * notices, because the only place it appears is inside other people's feeds.
 * So the generator records exactly what it rendered in og-image.meta.json, and
 * these tests assert those strings still match the constants the site is built
 * from. Change the positioning without running `npm run og-card` and the suite
 * fails — the same guarantee generating it during the build would give, without
 * making every Netlify build download a browser.
 *
 * This replaced a photograph of Zach busking with a classical guitar, 25% black
 * pillarbox bars, captioned "playing guitar in Valencia, Spain", served as the
 * preview for all fourteen routes including the CV.
 */

const root = join(__dirname, "..", "..");
const card = readFileSync(join(root, "public", "og-image.png"));
const meta = JSON.parse(
  readFileSync(join(root, "public", "og-image.meta.json"), "utf8"),
) as Record<string, string>;
const indexHtml = readFileSync(join(root, "index.html"), "utf8");

/** Width and height live in the IHDR chunk, bytes 16-24 of any PNG. */
function pngSize(bytes: Buffer) {
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
}

describe("social card", () => {
  it("is a PNG at exactly the dimensions the meta tags advertise", () => {
    expect(card.subarray(0, 8)).toEqual(
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    );
    expect(pngSize(card)).toEqual({ width: 1200, height: 630 });
    expect(indexHtml).toContain('<meta property="og:image:width" content="1200" />');
    expect(indexHtml).toContain('<meta property="og:image:height" content="630" />');
  });

  it("is small enough that scrapers with tight fetch budgets still take it", () => {
    // LinkedIn and Slack both cap what they will download for a preview; 1 MB
    // is the tightest commonly-cited limit and this sits far under it.
    expect(card.byteLength).toBeLessThan(1_000_000);
  });

  it("renders the same positioning the rest of the site claims", () => {
    expect(meta.name).toBe(CV_PROFILE.name);
    expect(meta.location).toBe(CV_PROFILE.location);
    // The card says "ML Engineer" where the CV says "Machine Learning
    // Engineer" — deliberate, because the long form is a 42-character unbroken
    // phrase that wraps badly at card scale. Assert the short form is a
    // faithful contraction rather than a different claim.
    expect(ROUTE_META.home.title).toContain(meta.title);
    expect(CV_PROFILE.headline).toContain("Data Scientist");
    expect(meta.title).toContain("Data Scientist");
  });

  it("is referenced by both og:image and twitter:image", () => {
    for (const tag of [
      '<meta property="og:image" content="https://zachscheffler.com/og-image.png">',
      '<meta name="twitter:image" content="https://zachscheffler.com/og-image.png">',
    ]) {
      expect(indexHtml).toContain(tag);
    }
  });

  it("has alt text that describes the card, not the page", () => {
    // The attribute carries "&amp;" where the rendered card carries "&", so
    // decode before comparing — otherwise this asserts on HTML escaping rather
    // than on what the card says.
    const alt = indexHtml
      .match(/<meta property="og:image:alt" content="([^"]*)"/)?.[1]
      ?.replace(/&amp;/g, "&");
    expect(alt, "og:image:alt not found in index.html").toBeTruthy();

    // The stamp plugin used to overwrite this with each route's title, so /cv
    // announced that its image depicted "CV | Zach Scheffler". Alt text
    // describes the picture; these are the words actually in it.
    expect(alt).toContain(meta.name);
    expect(alt).toContain(meta.title);
    expect(alt).toContain(meta.location);
    expect(alt).not.toContain("Valencia");
    expect(alt).not.toContain("guitar");
  });

  it("no longer ships the photograph it replaced", () => {
    expect(() => readFileSync(join(root, "public", "og-image.jpg"))).toThrow();
  });

  it("is the file public/_headers actually caches", () => {
    // Deleting og-image.jpg left the cache rule pointing at it, so the card
    // that ships was served with no Cache-Control at all — invisible, because
    // nothing renders a headers file. Pin the rule to the card's real name.
    const headers = readFileSync(join(root, "public", "_headers"), "utf8");
    expect(headers).toContain("/og-image.png");
    expect(headers).not.toContain("/og-image.jpg");
  });
});
