// GENERATED by scripts/generate-analytics-sparks.ts — do not hand-edit.
//
// Derived from public/data/spotify_songs.csv (the 2020 TidyTuesday Spotify
// sample) using the same src/lib functions /music-analytics runs on. Regenerate
// with `npx vite-node scripts/generate-analytics-sparks.ts`;
// src/content/analyticsSparks.test.ts fails if this file and the CSV disagree.

/** What each series actually is, for the copy that sits beside it. */
export const ANALYTICS_SPARK_META = {
  "rows": 32833,
  "artists": 10323,
  "months": 621,
  "from": "1957-01",
  "to": "2020-01"
} as const;

export const ANALYTICS_SPARKS = {
  /** Acquisition scores of the top artists by catalog size, best first. */
  acquisition: [61,60,59,53,53,51,49,49,41,37,36,35],
  /** Monthly modeled revenue for the whole sample, by release month. */
  revenue: [25023000,28992000,34248000,35895000,40956000,33177000,44901000,37014000,55905000,52335000,48111000,54375000,63882000,74388000,68970000,103755000,108309000,101577000,122367000,129042000,169794000,224097000,179655000,109416000],
  /** Rolling three-month variance of monthly streams, normalized. */
  risk: [0,0,1,0,0,0,1,1,3,3,0,0,2,3,1,10,14,0,3,6,20,68,25,100],
  /** Releases per year across the sample, most recent first. */
  catalog: [785,9081,3312,2430,2127,1779,1524,956],
} as const;
