/**
 * Derives the four sparklines on the homepage Intelligence band from the same
 * dataset /music-analytics runs on, and writes them to
 * src/content/analyticsSparks.ts.
 *
 * Why this exists: those four series were hand-written arrays sitting beside
 * four real statistical method names, under a heading about evaluating music
 * catalogs as financial assets. They were marked decorative and a screen
 * reader skipped them, but a sighted reviewer read four plotted series next
 * to "Revenue Forecasting / Linear Regression" and had no way to know the
 * numbers were invented.
 *
 * It imports src/lib rather than reimplementing anything, so the sparklines
 * cannot drift from the dashboard's own arithmetic. It is not part of the
 * build — the landing page must not pull a 820 KB CSV onto its scroll path,
 * which is the whole reason these are inline SVG and not recharts. The
 * committed output is guarded instead by src/content/analyticsSparks.test.ts,
 * which regenerates from the CSV and compares. Same contract as the social
 * card and scripts/generate-og-card.mjs.
 *
 *   npx vite-node scripts/generate-analytics-sparks.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { computeAnalyticsSparks } from "../src/content/analyticsSparksSource";

const root = join(import.meta.dirname, "..");
const csv = readFileSync(join(root, "public", "data", "spotify_songs.csv"), "utf8");
const { series, meta } = computeAnalyticsSparks(csv);

const file = `// GENERATED by scripts/generate-analytics-sparks.ts — do not hand-edit.
//
// Derived from public/data/spotify_songs.csv (the 2020 TidyTuesday Spotify
// sample) using the same src/lib functions /music-analytics runs on. Regenerate
// with \`npx vite-node scripts/generate-analytics-sparks.ts\`;
// src/content/analyticsSparks.test.ts fails if this file and the CSV disagree.

/** What each series actually is, for the copy that sits beside it. */
export const ANALYTICS_SPARK_META = ${JSON.stringify(meta, null, 2)} as const;

export const ANALYTICS_SPARKS = {
  /** Acquisition scores of the top artists by catalog size, best first. */
  acquisition: ${JSON.stringify(series.acquisition)},
  /** Monthly modeled revenue for the whole sample, by release month. */
  revenue: ${JSON.stringify(series.revenue)},
  /** Rolling three-month variance of monthly streams, normalized. */
  risk: ${JSON.stringify(series.risk)},
  /** Releases per year across the sample, most recent first. */
  catalog: ${JSON.stringify(series.catalog)},
} as const;
`;

writeFileSync(join(root, "src", "content", "analyticsSparks.ts"), file);
console.log("wrote src/content/analyticsSparks.ts");
for (const [k, v] of Object.entries(series)) console.log(`  ${k}: ${v.length} points`);
