export type Region =
  | "west_africa"
  | "balkans"
  | "flamenco"
  | "afro_cuban"
  | "brazil"
  | "india"
  | "middle_east"
  | "argentina"
  | "afro_peruvian"
  | "uruguay";

export type InstrumentRole =
  | "pulse"
  | "timeline"
  | "bass"
  | "slap"
  | "lead"
  | "texture";

export interface Timbre {
  id: string;
  name: string;
  instrument: string;
  role: InstrumentRole;
  midiNote: number;
}

export interface RhythmPattern {
  id: string;
  name: string;
  region: Region;
  country?: string;
  meter: string;
  subdivision: number[];
  tempoRange: [number, number];
  clave?: "2-3" | "3-2" | null;
  instruments: Timbre[];
  pattern: {
    [timbreId: string]: number[];
  };
  feel: "binary" | "ternary" | "swing" | "additive";
  tags: string[];
  source?: string;
}

export const REGIONS: Region[] = [
  "west_africa",
  "balkans",
  "flamenco",
  "afro_cuban",
  "brazil",
  "india",
  "middle_east",
  "argentina",
  "afro_peruvian",
  "uruguay",
];

export const REGION_LABELS: Record<Region, string> = {
  west_africa: "West Africa",
  balkans: "Balkans",
  flamenco: "Flamenco",
  afro_cuban: "Afro-Caribbean",
  brazil: "Brazil",
  india: "India",
  middle_east: "Middle East",
  argentina: "Argentina",
  afro_peruvian: "Afro-Peruvian",
  uruguay: "Uruguay",
};

const X = 1;
const x = 0.72;
const g = 0.42;
const _ = 0;

const WEST_AFRICA_TIMBRES: Timbre[] = [
  { id: "djembe_bass", name: "Djembe Bass", instrument: "Djembe", role: "bass", midiNote: 36 },
  { id: "djembe_slap", name: "Djembe Slap", instrument: "Djembe", role: "slap", midiNote: 39 },
  { id: "dunun_bell", name: "Dunun Bell", instrument: "Bell", role: "timeline", midiNote: 56 },
];

const BALKAN_TIMBRES: Timbre[] = [
  { id: "tupan_low", name: "Tupan Low", instrument: "Tupan", role: "bass", midiNote: 36 },
  { id: "tupan_high", name: "Tupan High", instrument: "Tupan", role: "lead", midiNote: 38 },
];

const FLAMENCO_TIMBRES: Timbre[] = [
  { id: "palmas", name: "Palmas", instrument: "Hands", role: "timeline", midiNote: 39 },
  { id: "cajon_low", name: "Cajon Low", instrument: "Cajon", role: "bass", midiNote: 36 },
  { id: "cajon_high", name: "Cajon High", instrument: "Cajon", role: "slap", midiNote: 38 },
];

const AFRO_CUBAN_TIMBRES: Timbre[] = [
  { id: "clave", name: "Clave", instrument: "Clave", role: "timeline", midiNote: 75 },
  { id: "conga-low", name: "Conga Tumba", instrument: "Conga", role: "bass", midiNote: 64 },
  { id: "conga-slap", name: "Conga Slap", instrument: "Conga", role: "slap", midiNote: 62 },
  { id: "campana", name: "Campana", instrument: "Bell", role: "pulse", midiNote: 56 },
];

const BRAZIL_TIMBRES: Timbre[] = [
  { id: "zabumba_low", name: "Zabumba Low", instrument: "Zabumba", role: "bass", midiNote: 36 },
  { id: "zabumba_high", name: "Zabumba High", instrument: "Zabumba", role: "slap", midiNote: 37 },
  { id: "triangle", name: "Triangle", instrument: "Triangle", role: "timeline", midiNote: 81 },
];

const INDIA_TIMBRES: Timbre[] = [
  { id: "tabla_bayan", name: "Tabla Bayan", instrument: "Tabla", role: "bass", midiNote: 36 },
  { id: "tabla_dayan", name: "Tabla Dayan", instrument: "Tabla", role: "lead", midiNote: 68 },
  { id: "konnakol", name: "Konnakol", instrument: "Voice", role: "timeline", midiNote: 39 },
];

const MIDDLE_EAST_TIMBRES: Timbre[] = [
  { id: "darbuka_dum", name: "Darbuka Dum", instrument: "Darbuka", role: "bass", midiNote: 36 },
  { id: "darbuka_tek", name: "Darbuka Tek", instrument: "Darbuka", role: "lead", midiNote: 42 },
  { id: "riq", name: "Riq", instrument: "Riq", role: "timeline", midiNote: 54 },
  { id: "frame_drum", name: "Frame Drum", instrument: "Frame Drum", role: "pulse", midiNote: 40 },
];

const ARGENTINA_TIMBRES: Timbre[] = [
  { id: "bombo_leguero_low", name: "Bombo Leguero Low", instrument: "Bombo Leguero", role: "bass", midiNote: 36 },
  { id: "bombo_leguero_high", name: "Bombo Leguero High", instrument: "Bombo Leguero", role: "lead", midiNote: 38 },
  { id: "bombo_leguero_rim", name: "Bombo Leguero Rim", instrument: "Bombo Leguero", role: "timeline", midiNote: 37 },
];

const PUERTO_RICO_TIMBRES: Timbre[] = [
  { id: "conga-low", name: "Buleador", instrument: "Barril", role: "bass", midiNote: 64 },
  { id: "conga-slap", name: "Subidor", instrument: "Barril", role: "lead", midiNote: 62 },
  { id: "cowbell", name: "Cua", instrument: "Sticks", role: "timeline", midiNote: 56 },
  { id: "shaker", name: "Maraca", instrument: "Maraca", role: "texture", midiNote: 70 },
];

const BRAZIL_SAMBA_TIMBRES: Timbre[] = [
  { id: "surdo", name: "Surdo", instrument: "Surdo", role: "bass", midiNote: 36 },
  { id: "repique", name: "Repique", instrument: "Repique", role: "lead", midiNote: 38 },
  { id: "agogo", name: "Agogo", instrument: "Agogo", role: "timeline", midiNote: 67 },
  { id: "palmas", name: "Palmas", instrument: "Hands", role: "texture", midiNote: 39 },
];

const AFRO_PERUVIAN_TIMBRES: Timbre[] = [
  { id: "cajon_low", name: "Cajon Bass", instrument: "Cajon", role: "bass", midiNote: 36 },
  { id: "cajon_high", name: "Cajon High", instrument: "Cajon", role: "lead", midiNote: 38 },
  { id: "cowbell", name: "Quijada", instrument: "Quijada", role: "timeline", midiNote: 56 },
  { id: "shaker", name: "Cajita", instrument: "Cajita", role: "texture", midiNote: 70 },
];

const URUGUAY_TIMBRES: Timbre[] = [
  { id: "surdo", name: "Tambor Piano", instrument: "Tambor Piano", role: "bass", midiNote: 36 },
  { id: "repique", name: "Tambor Repique", instrument: "Tambor Repique", role: "lead", midiNote: 38 },
  { id: "cowbell", name: "Madera", instrument: "Madera", role: "timeline", midiNote: 56 },
  { id: "conga-high", name: "Tambor Chico", instrument: "Tambor Chico", role: "pulse", midiNote: 60 },
];

export const RHYTHM_PATTERNS: RhythmPattern[] = [
  {
    id: "west_africa_kuku",
    name: "Kuku",
    region: "west_africa",
    country: "Guinea",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [96, 132],
    clave: null,
    instruments: WEST_AFRICA_TIMBRES,
    pattern: {
      djembe_bass: [X, _, _, g, _, _, X, _, _, g, _, _],
      djembe_slap: [_, _, X, _, X, _, _, _, X, _, X, _],
      dunun_bell: [X, _, x, _, X, _, x, _, X, _, x, _],
    },
    feel: "ternary",
    tags: ["dance", "guinea", "djembe", "intermediate"],
    source: "Guinean harvest dance rhythm",
  },
  {
    id: "west_africa_kpanlogo",
    name: "Kpanlogo",
    region: "west_africa",
    country: "Ghana",
    meter: "4/4",
    subdivision: [2, 2, 2, 2],
    tempoRange: [90, 120],
    clave: null,
    instruments: WEST_AFRICA_TIMBRES,
    pattern: {
      djembe_bass: [X, _, _, _, _, x, X, _],
      djembe_slap: [_, _, X, _, _, X, _, X],
      dunun_bell: [X, _, _, X, _, X, _, _],
    },
    feel: "swing",
    tags: ["groove", "ghana", "community", "beginner"],
    source: "Ga social groove from Accra",
  },
  {
    id: "west_africa_soli",
    name: "Soli",
    region: "west_africa",
    country: "Guinea",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [118, 154],
    clave: null,
    instruments: WEST_AFRICA_TIMBRES,
    pattern: {
      djembe_bass: [X, _, _, _, X, _, _, _, X, _, _, _],
      djembe_slap: [_, X, _, _, _, X, _, X, _, _, _, X],
      dunun_bell: [X, _, x, _, X, _, X, _, x, _, X, _],
    },
    feel: "ternary",
    tags: ["celebration", "guinea", "rite", "advanced"],
    source: "Manding initiation rhythm",
  },
  {
    id: "west_africa_foli",
    name: "Foli",
    region: "west_africa",
    country: "Guinea",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [98, 132],
    clave: null,
    instruments: WEST_AFRICA_TIMBRES,
    pattern: {
      djembe_bass: [X, _, _, _, X, _, _, _, X, _, _, _],
      djembe_slap: [_, X, _, _, _, X, _, X, _, _, _, X],
      dunun_bell: [X, _, x, _, X, _, x, _, X, _, X, _],
    },
    feel: "ternary",
    tags: ["foli", "guinea", "bell-pattern", "intermediate"],
    source: "Foli-inspired bell and djembe layering",
  },
  {
    id: "west_africa_timeline_in_six",
    name: "Timeline in Six",
    region: "west_africa",
    country: "Ghana",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [88, 116],
    clave: null,
    instruments: WEST_AFRICA_TIMBRES,
    pattern: {
      djembe_bass: [X, _, _, _, _, _, X, _, _, _, _, _],
      djembe_slap: [_, _, X, _, X, _, _, _, X, _, X, _],
      dunun_bell: [X, _, _, X, _, _, X, _, _, _, X, _],
    },
    feel: "ternary",
    tags: ["clave-in-6", "ghana", "timeline", "beginner"],
    source: "Six-pulse timeline study based on Afro-diasporic clave references",
  },
  {
    id: "balkans_kopanitsa",
    name: "Kopanitsa",
    region: "balkans",
    country: "Bulgaria",
    meter: "11/8",
    subdivision: [2, 2, 3, 2, 2],
    tempoRange: [100, 138],
    clave: null,
    instruments: BALKAN_TIMBRES,
    pattern: {
      tupan_low: [X, _, X, _, X, _, _, X, _, X, _],
      tupan_high: [_, X, _, X, _, X, _, _, X, _, X],
    },
    feel: "additive",
    tags: ["dance", "bulgaria", "odd-meter", "advanced"],
    source: "Bulgarian 11/8 dance groove",
  },
  {
    id: "balkans_cocek",
    name: "Cocek",
    region: "balkans",
    country: "North Macedonia",
    meter: "9/8",
    subdivision: [2, 2, 2, 3],
    tempoRange: [108, 148],
    clave: null,
    instruments: BALKAN_TIMBRES,
    pattern: {
      tupan_low: [X, _, X, _, X, _, X, _, _],
      tupan_high: [_, X, _, X, _, X, _, X, _],
    },
    feel: "additive",
    tags: ["brass", "north-macedonia", "odd-meter", "intermediate"],
    source: "Balkan brass dance pulse",
  },
  {
    id: "balkans_lesnoto",
    name: "Lesnoto",
    region: "balkans",
    country: "North Macedonia",
    meter: "7/8",
    subdivision: [3, 2, 2],
    tempoRange: [88, 124],
    clave: null,
    instruments: BALKAN_TIMBRES,
    pattern: {
      tupan_low: [X, _, _, X, _, X, _],
      tupan_high: [_, X, _, _, X, _, X],
    },
    feel: "additive",
    tags: ["dance", "north-macedonia", "odd-meter", "beginner"],
    source: "Common Balkan 7/8 dance cycle",
  },
  {
    id: "balkans_ruchenitsa",
    name: "Ruchenitsa",
    region: "balkans",
    country: "Bulgaria",
    meter: "7/8",
    subdivision: [2, 2, 3],
    tempoRange: [112, 148],
    clave: null,
    instruments: BALKAN_TIMBRES,
    pattern: {
      tupan_low: [X, _, X, _, X, _, _],
      tupan_high: [_, X, _, X, _, X, X],
    },
    feel: "additive",
    tags: ["dance", "bulgaria", "odd-meter", "intermediate"],
    source: "Bulgarian Ruchenitsa in 2+2+3",
  },
  {
    id: "balkans_paidushko",
    name: "Paidushko Horo",
    region: "balkans",
    country: "Bulgaria",
    meter: "5/8",
    subdivision: [2, 3],
    tempoRange: [112, 150],
    clave: null,
    instruments: BALKAN_TIMBRES,
    pattern: {
      tupan_low: [X, _, X, _, _],
      tupan_high: [_, X, _, X, X],
    },
    feel: "additive",
    tags: ["dance", "bulgaria", "odd-meter", "beginner"],
    source: "Paidushko Horo in 2+3",
  },
  {
    id: "balkans_daychovo",
    name: "Daychovo Horo",
    region: "balkans",
    country: "Bulgaria",
    meter: "9/8",
    subdivision: [2, 2, 2, 3],
    tempoRange: [96, 134],
    clave: null,
    instruments: BALKAN_TIMBRES,
    pattern: {
      tupan_low: [X, _, X, _, X, _, X, _, _],
      tupan_high: [_, X, _, X, _, X, _, X, X],
    },
    feel: "additive",
    tags: ["dance", "bulgaria", "odd-meter", "intermediate"],
    source: "Daychovo Horo with 2+2+2+3 pulse grouping",
  },
  {
    id: "balkans_buchimish",
    name: "Buchimish",
    region: "balkans",
    country: "Bulgaria",
    meter: "15/8",
    subdivision: [2, 2, 2, 2, 3, 2, 2],
    tempoRange: [84, 118],
    clave: null,
    instruments: BALKAN_TIMBRES,
    pattern: {
      tupan_low: [X, _, X, _, X, _, X, _, X, _, _, X, _, X, _],
      tupan_high: [_, X, _, X, _, X, _, X, _, X, X, _, X, _, X],
    },
    feel: "additive",
    tags: ["dance", "bulgaria", "odd-meter", "advanced"],
    source: "Buchimish cycle in 15/8",
  },
  {
    id: "flamenco_buleria",
    name: "Buleria",
    region: "flamenco",
    country: "Spain",
    meter: "12/8",
    subdivision: [3, 3, 2, 2, 2],
    tempoRange: [150, 220],
    clave: null,
    instruments: FLAMENCO_TIMBRES,
    pattern: {
      palmas: [X, _, _, X, _, _, X, _, X, _, X, _],
      cajon_low: [X, _, _, _, _, _, X, _, _, _, _, _],
      cajon_high: [_, _, X, _, _, X, _, _, X, _, X, _],
    },
    feel: "additive",
    tags: ["jerez", "compas", "dance", "advanced"],
    source: "12-beat buleria compas",
  },
  {
    id: "flamenco_solea",
    name: "Solea",
    region: "flamenco",
    country: "Spain",
    meter: "12/8",
    subdivision: [3, 3, 2, 2, 2],
    tempoRange: [92, 128],
    clave: null,
    instruments: FLAMENCO_TIMBRES,
    pattern: {
      palmas: [X, _, _, X, _, _, X, _, X, _, X, _],
      cajon_low: [X, _, _, _, _, _, _, _, X, _, _, _],
      cajon_high: [_, _, _, X, _, _, _, _, _, X, _, _],
    },
    feel: "additive",
    tags: ["cante-jondo", "compas", "spain", "intermediate"],
    source: "Traditional solea pulse",
  },
  {
    id: "flamenco_tangos",
    name: "Tangos",
    region: "flamenco",
    country: "Spain",
    meter: "4/4",
    subdivision: [2, 2, 2, 2],
    tempoRange: [108, 144],
    clave: null,
    instruments: FLAMENCO_TIMBRES,
    pattern: {
      palmas: [X, _, X, _, X, _, X, _],
      cajon_low: [X, _, _, X, X, _, _, X],
      cajon_high: [_, X, _, X, _, X, _, X],
    },
    feel: "binary",
    tags: ["groove", "cadiz", "dance", "beginner"],
    source: "Straight-ahead tangos compas",
  },
  {
    id: "flamenco_alegria",
    name: "Alegria",
    region: "flamenco",
    country: "Spain",
    meter: "12/8",
    subdivision: [3, 3, 2, 2, 2],
    tempoRange: [118, 156],
    clave: null,
    instruments: FLAMENCO_TIMBRES,
    pattern: {
      palmas: [X, _, _, X, _, _, X, _, X, _, X, _],
      cajon_low: [X, _, _, _, _, _, _, _, X, _, _, _],
      cajon_high: [_, _, X, _, X, _, _, _, X, _, X, _],
    },
    feel: "additive",
    tags: ["alegria", "compas", "cadiz", "intermediate"],
    source: "Alegria compas with upbeat palmas phrasing",
  },
  {
    id: "flamenco_tanguillos",
    name: "Tanguillos",
    region: "flamenco",
    country: "Spain",
    meter: "6/8",
    subdivision: [3, 3],
    tempoRange: [124, 164],
    clave: null,
    instruments: FLAMENCO_TIMBRES,
    pattern: {
      palmas: [_, X, _, X, _, _],
      cajon_low: [X, _, _, _, X, _],
      cajon_high: [_, _, X, _, _, X],
    },
    feel: "ternary",
    tags: ["tanguillos", "cadiz", "dance", "intermediate"],
    source: "Tanguillos hand-clap and cajon conversation",
  },
  {
    id: "flamenco_seguiriya",
    name: "Seguiriya",
    region: "flamenco",
    country: "Spain",
    meter: "12/8",
    subdivision: [2, 2, 3, 2, 3],
    tempoRange: [86, 118],
    clave: null,
    instruments: FLAMENCO_TIMBRES,
    pattern: {
      palmas: [X, _, X, _, _, X, _, X, _, _, X, _],
      cajon_low: [X, _, _, _, X, _, _, _, X, _, _, _],
      cajon_high: [_, _, X, _, _, _, X, _, _, X, _, _],
    },
    feel: "additive",
    tags: ["seguiriya", "cante-jondo", "compas", "advanced"],
    source: "Seguiriya compas with shifted accent cycle",
  },
  {
    id: "afro_cuban_son_23",
    name: "Son Clave 2-3",
    region: "afro_cuban",
    country: "Cuba",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [90, 136],
    clave: "2-3",
    instruments: AFRO_CUBAN_TIMBRES,
    pattern: {
      clave: [X, _, _, X, _, _, X, _, _, _, X, _, X, _, _, _],
      "conga-low": [X, _, _, _, _, _, x, _, _, _, X, _, _, _, x, _],
      "conga-slap": [_, _, x, _, X, _, _, _, _, _, x, _, _, X, _, _],
      campana: [X, _, _, _, X, _, _, _, X, _, _, _, X, _, _, _],
    },
    feel: "swing",
    tags: ["son", "cuba", "clave", "intermediate"],
    source: "Son clave in 2-3 direction",
  },
  {
    id: "afro_cuban_son_32",
    name: "Son Clave 3-2",
    region: "afro_cuban",
    country: "Cuba",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [88, 126],
    clave: "3-2",
    instruments: AFRO_CUBAN_TIMBRES,
    pattern: {
      clave: [X, _, _, X, _, _, _, X, _, _, X, _, _, X, _, _],
      "conga-low": [X, _, _, _, _, _, x, _, X, _, _, _, _, _, x, _],
      "conga-slap": [_, _, x, _, _, _, X, _, _, _, x, _, _, _, X, _],
      campana: [X, _, _, _, X, _, _, _, X, _, X, _, _, _, X, _],
    },
    feel: "swing",
    tags: ["son", "cuba", "clave", "intermediate"],
    source: "Son clave in 3-2 direction",
  },
  {
    id: "afro_cuban_guaguanco",
    name: "Guaguanco",
    region: "afro_cuban",
    country: "Cuba",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [80, 108],
    clave: "3-2",
    instruments: AFRO_CUBAN_TIMBRES,
    pattern: {
      clave: [X, _, _, X, _, _, _, X, _, _, X, _, X, _, _, _],
      "conga-low": [X, _, _, _, x, _, _, _, X, _, _, _, x, _, _, _],
      "conga-slap": [_, _, _, _, _, _, _, X, _, _, _, _, _, X, _, _],
      campana: [_, _, _, _, X, _, _, X, _, _, X, _, _, X, _, _],
    },
    feel: "binary",
    tags: ["rumba", "cuba", "clave", "advanced"],
    source: "Rumba guaguanco cask-and-conga texture",
  },
  {
    id: "afro_cuban_cha_cha_cha",
    name: "Cha Cha Cha",
    region: "afro_cuban",
    country: "Cuba",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [112, 132],
    clave: "2-3",
    instruments: AFRO_CUBAN_TIMBRES,
    pattern: {
      clave: [X, _, _, X, _, _, X, _, _, _, X, _, X, _, _, _],
      "conga-low": [X, _, _, _, _, _, x, _, X, _, _, _, _, _, x, _],
      "conga-slap": [_, _, _, X, _, _, _, _, _, _, _, X, _, _, _, X],
      campana: [_, _, X, _, _, _, X, _, _, _, X, _, _, _, X, _],
    },
    feel: "binary",
    tags: ["cha-cha-cha", "cuba", "dance", "beginner"],
    source: "Cha cha cha groove built around the son-clave side",
  },
  {
    id: "afro_cuban_mozambique",
    name: "Mozambique",
    region: "afro_cuban",
    country: "Cuba",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [108, 138],
    clave: "3-2",
    instruments: AFRO_CUBAN_TIMBRES,
    pattern: {
      clave: [X, _, _, X, _, _, _, X, _, _, X, _, _, X, _, _],
      "conga-low": [X, _, _, _, X, _, _, _, _, _, X, _, X, _, _, _],
      "conga-slap": [_, _, X, _, _, X, _, _, _, _, _, X, _, _, X, _],
      campana: [X, _, X, _, _, X, _, X, _, _, X, _, X, _, _, X],
    },
    feel: "swing",
    tags: ["mozambique", "cuba", "bell", "advanced"],
    source: "Mozambique bell and drum phrasing inspired by festival arrangements",
  },
  {
    id: "afro_cuban_bomba_sica",
    name: "Bomba Sica",
    region: "afro_cuban",
    country: "Puerto Rico",
    meter: "4/4",
    subdivision: [2, 2, 2, 2],
    clave: null,
    tempoRange: [94, 124],
    instruments: PUERTO_RICO_TIMBRES,
    pattern: {
      "conga-low": [X, _, _, X, X, _, _, X],
      "conga-slap": [_, _, X, _, _, X, _, _],
      cowbell: [X, _, X, _, X, _, X, _],
      shaker: [x, x, x, x, x, x, x, x],
    },
    feel: "binary",
    tags: ["bomba", "puerto-rico", "dance", "intermediate"],
    source: "Puerto Rican bomba sica groove translated for barril roles",
  },
  {
    id: "afro_cuban_bomba_yuba",
    name: "Bomba Yuba",
    region: "afro_cuban",
    country: "Puerto Rico",
    meter: "6/8",
    subdivision: [3, 3],
    clave: null,
    tempoRange: [72, 102],
    instruments: PUERTO_RICO_TIMBRES,
    pattern: {
      "conga-low": [X, _, _, X, _, _],
      "conga-slap": [_, X, _, _, X, _],
      cowbell: [X, _, X, _, X, _],
      shaker: [x, _, x, x, _, x],
    },
    feel: "ternary",
    tags: ["bomba", "puerto-rico", "yuba", "advanced"],
    source: "Slow bomba yuba with dialogic barril phrasing",
  },
  {
    id: "afro_cuban_plena",
    name: "Plena",
    region: "afro_cuban",
    country: "Puerto Rico",
    meter: "4/4",
    subdivision: [2, 2, 2, 2],
    clave: null,
    tempoRange: [100, 132],
    instruments: PUERTO_RICO_TIMBRES,
    pattern: {
      "conga-low": [X, _, _, X, X, _, _, X],
      "conga-slap": [_, X, _, _, _, X, _, X],
      cowbell: [X, _, _, X, _, X, _, _],
      shaker: [x, x, x, x, x, x, x, x],
    },
    feel: "binary",
    tags: ["plena", "puerto-rico", "song-form", "beginner"],
    source: "Pandereta-inspired plena pulse adapted to the engine grid",
  },
  {
    id: "brazil_baiao",
    name: "Baiao",
    region: "brazil",
    country: "Brazil",
    meter: "2/4",
    subdivision: [4, 4],
    tempoRange: [108, 136],
    clave: null,
    instruments: BRAZIL_TIMBRES,
    pattern: {
      zabumba_low: [X, _, _, _, _, _, X, _],
      zabumba_high: [_, _, _, _, _, _, _, X],
      triangle: [X, _, x, X, _, x, X, _],
    },
    feel: "swing",
    tags: ["northeast", "forro", "brazil", "beginner"],
    source: "Luiz Gonzaga-style baiao",
  },
  {
    id: "brazil_xote",
    name: "Xote",
    region: "brazil",
    country: "Brazil",
    meter: "4/4",
    subdivision: [2, 2, 2, 2],
    tempoRange: [84, 110],
    clave: null,
    instruments: BRAZIL_TIMBRES,
    pattern: {
      zabumba_low: [X, _, X, _, X, _, X, _],
      zabumba_high: [_, _, X, _, _, _, X, _],
      triangle: [X, _, x, _, X, _, x, _],
    },
    feel: "binary",
    tags: ["forro", "brazil", "dance", "beginner"],
    source: "Even xote pulse with zabumba and triangle",
  },
  {
    id: "brazil_coco",
    name: "Coco",
    region: "brazil",
    country: "Brazil",
    meter: "4/4",
    subdivision: [2, 2, 2, 2],
    tempoRange: [100, 132],
    clave: null,
    instruments: BRAZIL_TIMBRES,
    pattern: {
      zabumba_low: [X, _, _, X, X, _, _, X],
      zabumba_high: [_, _, _, X, _, _, _, _],
      triangle: [X, _, x, X, _, x, X, _],
    },
    feel: "swing",
    tags: ["northeast", "brazil", "circle-dance", "intermediate"],
    source: "Northeastern coco groove",
  },
  {
    id: "brazil_samba_de_roda",
    name: "Samba de Roda",
    region: "brazil",
    country: "Brazil",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [98, 126],
    clave: null,
    instruments: BRAZIL_SAMBA_TIMBRES,
    pattern: {
      surdo: [X, _, _, _, X, _, _, _, X, _, _, _, X, _, _, _],
      repique: [_, _, X, _, _, X, _, X, _, _, X, _, _, X, _, X],
      agogo: [X, _, x, _, X, _, x, _, X, _, x, _, X, _, x, _],
      palmas: [_, X, _, X, _, X, _, X, _, X, _, X, _, X, _, X],
    },
    feel: "swing",
    tags: ["samba-de-roda", "bahia", "circle", "intermediate"],
    source: "Bahian samba de roda ensemble pulse",
  },
  {
    id: "brazil_bossa_nova",
    name: "Bossa Nova",
    region: "brazil",
    country: "Brazil",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [72, 108],
    clave: null,
    instruments: BRAZIL_SAMBA_TIMBRES,
    pattern: {
      surdo: [X, _, _, _, _, _, X, _, X, _, _, _, _, _, X, _],
      repique: [_, _, _, X, _, _, _, _, _, _, _, X, _, _, _, _],
      agogo: [X, _, _, X, _, _, X, _, _, X, _, _, X, _, _, X],
      palmas: [_, _, x, _, _, _, x, _, _, _, x, _, _, _, x, _],
    },
    feel: "swing",
    tags: ["bossa-nova", "brazil", "syncopation", "intermediate"],
    source: "Clave-informed bossa nova phrasing",
  },
  {
    id: "india_teentaal",
    name: "Teentaal",
    region: "india",
    country: "India",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [78, 118],
    clave: null,
    instruments: INDIA_TIMBRES,
    pattern: {
      tabla_bayan: [X, _, _, _, X, _, _, _, X, _, _, _, X, _, _, _],
      tabla_dayan: [_, X, _, X, _, X, _, X, _, X, _, X, _, X, _, X],
      konnakol: [X, _, X, _, X, _, X, _, X, _, X, _, X, _, X, _],
    },
    feel: "binary",
    tags: ["tala", "hindustani", "india", "intermediate"],
    source: "Sixteen-beat teentaal theka",
  },
  {
    id: "india_keharwa",
    name: "Keharwa",
    region: "india",
    country: "India",
    meter: "4/4",
    subdivision: [4, 4],
    tempoRange: [90, 130],
    clave: null,
    instruments: INDIA_TIMBRES,
    pattern: {
      tabla_bayan: [X, _, _, _, X, _, _, _],
      tabla_dayan: [_, X, _, X, _, _, X, _],
      konnakol: [X, X, _, X, X, _, X, _],
    },
    feel: "binary",
    tags: ["tala", "folk", "india", "beginner"],
    source: "Eight-beat keharwa cycle",
  },
  {
    id: "india_rupak",
    name: "Rupak",
    region: "india",
    country: "India",
    meter: "7/8",
    subdivision: [3, 2, 2],
    tempoRange: [72, 108],
    clave: null,
    instruments: INDIA_TIMBRES,
    pattern: {
      tabla_bayan: [X, _, _, X, _, X, _],
      tabla_dayan: [_, X, X, _, X, _, X],
      konnakol: [X, _, X, X, _, X, _],
    },
    feel: "additive",
    tags: ["tala", "hindustani", "india", "advanced"],
    source: "Seven-beat rupak tala",
  },
  {
    id: "india_jhaptaal",
    name: "Jhaptaal",
    region: "india",
    country: "India",
    meter: "10/8",
    subdivision: [2, 3, 2, 3],
    tempoRange: [72, 104],
    clave: null,
    instruments: INDIA_TIMBRES,
    pattern: {
      tabla_bayan: [X, _, X, _, _, X, _, X, _, _],
      tabla_dayan: [_, X, _, X, X, _, X, _, X, X],
      konnakol: [X, _, X, _, X, X, _, X, _, X],
    },
    feel: "additive",
    tags: ["tala", "hindustani", "jhaptaal", "advanced"],
    source: "Ten-beat jhaptaal grouped 2+3+2+3",
  },
  {
    id: "india_adi_tala",
    name: "Adi Tala",
    region: "india",
    country: "India",
    meter: "8/8",
    subdivision: [4, 2, 2],
    tempoRange: [82, 118],
    clave: null,
    instruments: INDIA_TIMBRES,
    pattern: {
      tabla_bayan: [X, _, _, _, X, _, X, _],
      tabla_dayan: [_, X, _, X, _, X, _, X],
      konnakol: [X, _, X, _, X, _, X, _],
    },
    feel: "binary",
    tags: ["tala", "carnatic", "adi-tala", "beginner"],
    source: "Eight-beat Adi Tala counting cycle",
  },
  {
    id: "middle_east_maqsum",
    name: "Maqsum",
    region: "middle_east",
    country: "Egypt",
    meter: "4/4",
    subdivision: [2, 2, 2, 2],
    tempoRange: [80, 118],
    clave: null,
    instruments: MIDDLE_EAST_TIMBRES,
    pattern: {
      darbuka_dum: [X, _, _, _, X, _, _, _],
      darbuka_tek: [_, _, X, _, _, X, _, X],
      riq: [X, _, X, _, X, _, X, _],
      frame_drum: [X, _, _, X, _, _, X, _],
    },
    feel: "binary",
    tags: ["egypt", "baladi", "groove", "beginner"],
    source: "Canonical maqsum rhythm",
  },
  {
    id: "middle_east_malfuf",
    name: "Malfuf",
    region: "middle_east",
    country: "Lebanon",
    meter: "2/4",
    subdivision: [2, 2],
    tempoRange: [102, 138],
    clave: null,
    instruments: MIDDLE_EAST_TIMBRES,
    pattern: {
      darbuka_dum: [X, _, _, X],
      darbuka_tek: [_, X, _, X],
      riq: [X, _, X, _],
      frame_drum: [X, _, _, _],
    },
    feel: "binary",
    tags: ["levant", "dance", "groove", "beginner"],
    source: "Fast entrance rhythm for Levantine music",
  },
  {
    id: "middle_east_samai",
    name: "Samai Thaqil",
    region: "middle_east",
    country: "Turkey",
    meter: "10/8",
    subdivision: [3, 2, 2, 3],
    tempoRange: [60, 88],
    clave: null,
    instruments: MIDDLE_EAST_TIMBRES,
    pattern: {
      darbuka_dum: [X, _, _, _, X, _, X, _, _, _],
      darbuka_tek: [_, _, X, _, _, X, _, _, _, X],
      riq: [X, _, X, _, X, _, X, _, X, _],
      frame_drum: [X, _, _, X, _, _, X, _, _, X],
    },
    feel: "additive",
    tags: ["classical", "turkey", "odd-meter", "advanced"],
    source: "Ottoman samai usul",
  },
  {
    id: "argentina_chacarera",
    name: "Chacarera",
    region: "argentina",
    country: "Argentina",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [110, 142],
    clave: null,
    instruments: ARGENTINA_TIMBRES,
    pattern: {
      bombo_leguero_low: [X, _, _, X, _, _, X, _, _, X, _, _],
      bombo_leguero_high: [_, _, X, _, _, _, _, _, X, _, _, _],
      bombo_leguero_rim: [_, X, _, _, X, _, _, X, _, _, X, _],
    },
    feel: "ternary",
    tags: ["folk", "santiago-del-estero", "argentina", "beginner"],
    source: "Traditional chacarera pulse",
  },
  {
    id: "argentina_zamba",
    name: "Zamba",
    region: "argentina",
    country: "Argentina",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [80, 110],
    clave: null,
    instruments: ARGENTINA_TIMBRES,
    pattern: {
      bombo_leguero_low: [X, _, _, _, _, X, _, _, X, _, _, _],
      bombo_leguero_high: [_, _, X, _, _, _, _, _, x, _, _, _],
      bombo_leguero_rim: [_, X, _, _, _, X, _, _, _, X, _, _],
    },
    feel: "ternary",
    tags: ["folk", "argentina", "song-form", "intermediate"],
    source: "Argentine zamba accompaniment groove",
  },
  {
    id: "argentina_malambo",
    name: "Malambo",
    region: "argentina",
    country: "Argentina",
    meter: "2/4",
    subdivision: [4, 4],
    tempoRange: [120, 160],
    clave: null,
    instruments: ARGENTINA_TIMBRES,
    pattern: {
      bombo_leguero_low: [X, _, X, _, X, _, X, _],
      bombo_leguero_high: [_, X, _, X, _, X, _, X],
      bombo_leguero_rim: [X, _, _, X, X, _, _, X],
    },
    feel: "binary",
    tags: ["dance", "argentina", "percussive", "advanced"],
    source: "Fast malambo bombo pattern",
  },
  {
    id: "argentina_vidala",
    name: "Vidala",
    region: "argentina",
    country: "Argentina",
    meter: "3/4",
    subdivision: [3],
    tempoRange: [68, 92],
    clave: null,
    instruments: ARGENTINA_TIMBRES,
    pattern: {
      bombo_leguero_low: [X, _, _],
      bombo_leguero_high: [_, _, x],
      bombo_leguero_rim: [_, X, _],
    },
    feel: "binary",
    tags: ["folk", "argentina", "song-form", "beginner"],
    source: "Slow vidala pulse for bombo leguero",
  },
  {
    id: "afro_peruvian_marinera_limenia",
    name: "Marinera Limenia",
    region: "afro_peruvian",
    country: "Peru",
    meter: "6/8",
    subdivision: [3, 3],
    tempoRange: [86, 118],
    clave: null,
    instruments: AFRO_PERUVIAN_TIMBRES,
    pattern: {
      cajon_low: [X, _, _, X, _, _],
      cajon_high: [_, _, X, _, X, _],
      cowbell: [X, _, X, _, X, _],
      shaker: [x, _, x, x, _, x],
    },
    feel: "ternary",
    tags: ["marinera", "peru", "cajon", "intermediate"],
    source: "Afro-Peruvian marinera limenia cajon phrasing",
  },
  {
    id: "afro_peruvian_marinera_nortena",
    name: "Marinera Nortena",
    region: "afro_peruvian",
    country: "Peru",
    meter: "6/8",
    subdivision: [3, 3],
    tempoRange: [96, 128],
    clave: null,
    instruments: AFRO_PERUVIAN_TIMBRES,
    pattern: {
      cajon_low: [X, _, _, X, _, _],
      cajon_high: [_, X, _, _, X, X],
      cowbell: [X, _, X, _, X, _],
      shaker: [x, x, _, x, x, _],
    },
    feel: "ternary",
    tags: ["marinera", "peru", "cajon", "advanced"],
    source: "Marinera nortena with denser upper cajon accents",
  },
  {
    id: "afro_peruvian_festejo",
    name: "Festejo",
    region: "afro_peruvian",
    country: "Peru",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [102, 138],
    clave: null,
    instruments: AFRO_PERUVIAN_TIMBRES,
    pattern: {
      cajon_low: [X, _, _, X, _, _, X, _, _, X, _, _],
      cajon_high: [_, X, _, _, X, _, _, _, X, _, X, _],
      cowbell: [X, _, x, _, X, _, x, _, X, _, x, _],
      shaker: [x, _, x, x, _, x, x, _, x, x, _, x],
    },
    feel: "ternary",
    tags: ["festejo", "peru", "dance", "intermediate"],
    source: "Festejo groove using cajon, quijada, and cajita layers",
  },
  {
    id: "afro_peruvian_lando",
    name: "Lando",
    region: "afro_peruvian",
    country: "Peru",
    meter: "12/8",
    subdivision: [3, 3, 3, 3],
    tempoRange: [72, 102],
    clave: null,
    instruments: AFRO_PERUVIAN_TIMBRES,
    pattern: {
      cajon_low: [X, _, _, _, _, X, _, _, X, _, _, _],
      cajon_high: [_, _, X, _, _, _, _, X, _, _, X, _],
      cowbell: [X, _, _, X, _, _, X, _, _, _, X, _],
      shaker: [x, _, _, x, _, x, x, _, _, x, _, x],
    },
    feel: "ternary",
    tags: ["lando", "peru", "cajon", "advanced"],
    source: "Slow lando with suspended 12/8 feel",
  },
  {
    id: "uruguay_candombe_base",
    name: "Candombe Base",
    region: "uruguay",
    country: "Uruguay",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [92, 122],
    clave: "3-2",
    instruments: URUGUAY_TIMBRES,
    pattern: {
      surdo: [X, _, _, _, X, _, _, _, X, _, _, _, X, _, _, _],
      repique: [_, _, X, _, _, X, _, _, _, _, X, _, _, X, _, _],
      cowbell: [X, _, _, X, _, _, _, X, _, _, X, _, _, X, _, _],
      "conga-high": [x, _, x, _, x, _, x, _, x, _, x, _, x, _, x, _],
    },
    feel: "swing",
    tags: ["candombe", "uruguay", "clave", "intermediate"],
    source: "Candombe base pattern using madera and drum-family roles",
  },
  {
    id: "uruguay_candombe_llamada",
    name: "Candombe Llamada",
    region: "uruguay",
    country: "Uruguay",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [100, 128],
    clave: "3-2",
    instruments: URUGUAY_TIMBRES,
    pattern: {
      surdo: [X, _, _, _, X, _, _, _, _, _, X, _, X, _, _, _],
      repique: [_, X, _, _, _, X, _, X, _, _, X, _, _, X, _, X],
      cowbell: [X, _, _, X, _, _, _, X, _, _, X, _, X, _, _, _],
      "conga-high": [x, _, x, _, x, _, x, _, x, _, x, _, x, _, x, _],
    },
    feel: "swing",
    tags: ["candombe", "uruguay", "llamada", "advanced"],
    source: "More animated llamada-style candombe variation",
  },
  {
    id: "uruguay_candombe_porton",
    name: "Se Abre el Porton",
    region: "uruguay",
    country: "Uruguay",
    meter: "4/4",
    subdivision: [4, 4, 4, 4],
    tempoRange: [102, 132],
    clave: "3-2",
    instruments: URUGUAY_TIMBRES,
    pattern: {
      surdo: [X, _, _, _, _, _, X, _, X, _, _, _, X, _, _, _],
      repique: [_, _, X, _, _, X, _, _, _, X, _, X, _, _, X, _],
      cowbell: [X, _, _, X, _, _, _, X, _, _, _, X, _, _, X, _],
      "conga-high": [x, _, x, _, x, _, x, _, x, _, x, _, x, _, x, _],
    },
    feel: "swing",
    tags: ["candombe", "uruguay", "fatorusso", "advanced"],
    source: "Candombe variation linked to Se Abre el Porton",
  },
];

export function formatRegion(region: Region): string {
  return REGION_LABELS[region];
}

export function filterRhythms({
  region,
  bpm,
  tags,
}: {
  region: Region;
  bpm?: number | null;
  tags?: string[] | null;
}): RhythmPattern[] {
  return RHYTHM_PATTERNS.filter((rhythm) =>
    rhythm.region === region &&
    (!bpm || (rhythm.tempoRange[0] <= bpm && rhythm.tempoRange[1] >= bpm)) &&
    (!tags || tags.length === 0 || tags.every((tag) => rhythm.tags.includes(tag)))
  );
}
